apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-tests
spec:
  backoffLimit: 0  # Don't retry on failure
  template:
    spec:
      containers:
      - name: playwright
        image: automation:latest
        imagePullPolicy: Never
        env:
        - name: CI
          value: "true"
        volumeMounts:
        - name: playwright-report
          mountPath: /app/playwright-report
      volumes:
      - name: playwright-report
        persistentVolumeClaim:
          claimName: playwright-report-pvc
      restartPolicy: Never  # Required for Jobs. Options: Never or OnFailureclear